<template>
    <div class="loadingio-spinner-dual-ring-6oyplpxd25a">
        <div class="ldio-3ovz3unfho7">
            <div></div>
            <div>
                <div></div>
            </div>
        </div>
    </div>
</template>
<style type="text/css">
@keyframes ldio-3ovz3unfho7 {
    0% {
        transform: rotate(0)
    }

    100% {
        transform: rotate(360deg)
    }
}

.ldio-3ovz3unfho7 div {
    box-sizing: border-box !important
}

.ldio-3ovz3unfho7>div {
    position: absolute;
    width: 144px;
    height: 144px;
    top: 28px;
    left: 28px;
    border-radius: 50%;
    border: 16px solid #000;
    border-color: #c82f8e transparent #c82f8e transparent;
    animation: ldio-3ovz3unfho7 1s linear infinite;
}

.ldio-3ovz3unfho7>div:nth-child(2) {
    border-color: transparent
}

.ldio-3ovz3unfho7>div:nth-child(2) div {
    position: absolute;
    width: 100%;
    height: 100%;
    transform: rotate(45deg);
}

.ldio-3ovz3unfho7>div:nth-child(2) div:before,
.ldio-3ovz3unfho7>div:nth-child(2) div:after {
    content: "";
    display: block;
    position: absolute;
    width: 16px;
    height: 16px;
    top: -16px;
    left: 48px;
    background: #c82f8e;
    border-radius: 50%;
    box-shadow: 0 128px 0 0 #c82f8e;
}

.ldio-3ovz3unfho7>div:nth-child(2) div:after {
    left: -16px;
    top: 48px;
    box-shadow: 128px 0 0 0 #c82f8e;
}

.loadingio-spinner-dual-ring-6oyplpxd25a {
    width: 200px;
    height: 200px;
    display: inline-block;
    overflow: hidden;
    background: none;
}

.ldio-3ovz3unfho7 {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0;
    /* see note above */
}

.ldio-3ovz3unfho7 div {
    box-sizing: content-box;
}

/* generated by https://loading.io/ */</style>